services:
  db:
    image: mysql:8.0
    container_name: FilmesDb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filme
    ports:
      - "3306:3306"
    volumes:
      - readetrabalho_db_data:/var/lib/mysql

volumes:
  readetrabalho_db_data:
    external: true
